### ISSUE TITLE
Fails Codename One compilation on Android 29

### ISSUE THREAD

**Issue by jeeneeno** [jsfan3/CN1Libs-VideoOptimizer#5]
The following errors are generated  when sending a build to CN1 :

/home/ec2-user/.gradle/caches/transforms-1/files-1.1/jetified-mobile-ffmpeg.aar/18ebf87419f30dcb6e6aefd9a22390bc/res/values/values.xml:6:5-11:13: AAPT: Error retrieving parent for item: No resource found that matches the given name 'Theme.AppCompat.Light.DarkActionBar'.
    
/home/ec2-user/.gradle/caches/transforms-1/files-1.1/jetified-mobile-ffmpeg.aar/18ebf87419f30dcb6e6aefd9a22390bc/res/values/values.xml:6:5-11:13: AAPT: Error retrieving parent for item: No resource found that matches the given name 'Theme.AppCompat.Light.DarkActionBar'.
    
/home/ec2-user/.gradle/caches/transforms-1/files-1.1/jetified-mobile-ffmpeg.aar/18ebf87419f30dcb6e6aefd9a22390bc/res/values/values.xml:6:5-11:13: AAPT: No resource found that matches the given name: attr 'colorAccent'.
    
/home/ec2-user/.gradle/caches/transforms-1/files-1.1/jetified-mobile-ffmpeg.aar/18ebf87419f30dcb6e6aefd9a22390bc/res/values/values.xml:6:5-11:13: AAPT: No resource found that matches the given name: attr 'colorPrimary'.
    
/home/ec2-user/.gradle/caches/transforms-1/files-1.1/jetified-mobile-ffmpeg.aar/18ebf87419f30dcb6e6aefd9a22390bc/res/values/values.xml:6:5-11:13: AAPT: No resource found that matches the given name: attr 'colorPrimaryDark'.
    
/home/ec2-user/.gradle/caches/transforms-1/files-1.1/jetified-mobile-ffmpeg.aar/18ebf87419f30dcb6e6aefd9a22390bc/res/values/values.xml:6:5-11:13: AAPT: No resource found that matches the given name: attr 'colorAccent'.
    
/home/ec2-user/.gradle/caches/transforms-1/files-1.1/jetified-mobile-ffmpeg.aar/18ebf87419f30dcb6e6aefd9a22390bc/res/values/values.xml:6:5-11:13: AAPT: No resource found that matches the given name: attr 'colorPrimary'.
    
/home/ec2-user/.gradle/caches/transforms-1/files-1.1/jetified-mobile-ffmpeg.aar/18ebf87419f30dcb6e6aefd9a22390bc/res/values/values.xml:6:5-11:13: AAPT: No resource found that matches the given name: attr 'colorPrimaryDark'.

**Comment by jsfan3** [comment]
I apologize for the late reply, the notification of your message was among other notifications.

I've just sent an iOS and an Android build of a Maven project containing my VideoOptimizer cn1lib. The builds were compiled without any error (I used the migration tool of Steve, previously this was an Ant project).

Do you have the build hints `android.min_sdk_version=24` and `android.multidex=true`?
Have you migrated to Maven?

Have you tried the cn1lib in a new bare bones project downloaded from https://start.codenameone.com/?

I don't guess what could be the cause of the errors you reported.

**Comment by jsfan3** [comment]
If you have the build hint `android.buildToolsVersion=28` or `android.buildToolsVersion=29`, please remove it.

**Comment by jeeneeno** [comment]
Hi

Thank you for your reply.

I removed the build hint "android.buildToolsVersion=29" and all appears well :-)

Thank you.
